# -*- coding: utf-8 -*-
"""helloworld_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4VT_Jhs4FkqT2FGlEBI5GAuoi3ASxIw
"""

print("Hello World")